--
-- FILE: database_schema.sql
-- PROJECT: JSAT - Java Skill Assessment Tool
-- BACKEND: Supabase (PostgreSQL)
-- PURPOSE: Single source of truth for schema, RLS, and Auth integration.
--

-- ====================================================================
-- 1. ENUMS AND TYPES
-- ====================================================================

-- Define fixed values for question difficulty
CREATE TYPE difficulty_level AS ENUM ('Beginner','Novice','Intermediate','Advanced','Expert');
-- CREATE TYPE level_status_enum AS ENUM ('Beginner','Novice','Intermediate','Advanced','Expert');


-- ====================================================================
-- 2. CORE TABLES & RLS SETUP
-- ====================================================================

-- PROFILES: Links Supabase Auth to application roles.
CREATE TABLE profiles (
    -- PK is a FK to the built-in auth.users table
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY, 
    
    -- Role is essential for RLS and app logic. Defaults to 'candidate' on creation.
    role TEXT NOT NULL DEFAULT 'candidate' CHECK (role IN ('candidate', 'recruiter', 'admin')),
    
    -- The gatekeeper flag. FALSE until the user finalizes their role.
    is_role_finalized BOOLEAN NOT NULL DEFAULT FALSE,

    first_name TEXT,
    last_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure RLS is enabled on all security-critical tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- ====================================================================
-- 3. ASSESSMENT TABLES
-- ====================================================================
-- Level Tables 
CREATE TABLE level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Profile_id UUID REFERENCES profiles(id),
    Level_status difficulty_level ,
    Progress BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
--ALTER TABLE level_status ENABLE ROW LEVEL SECURITY; -- Enable RLS for Level Status

-- QUESTIONS TABLE
CREATE TABLE Question (
    Question_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Title text,
    Question TEXT NOT NULL,
    Input TEXT,
    Output TEXT,
    Category TEXT,
    Answer TEXT,
    difficulty difficulty_level NOT NULL
);
--ALTER TABLE questions ENABLE ROW LEVEL SECURITY; -- Enable RLS for Questions

-- EXAMS TABLE
CREATE TABLE Evaluation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Question_id BIGINT REFERENCES Question(Question_id) NOT NULL,
    Correctness BIGINT,
    Line_code BIGINT,
    Time_taken BIGINT,
    Runtime BIGINT,
    Error_made BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
--ALTER TABLE exams ENABLE ROW LEVEL SECURITY; -- Enable RLS for Exams

-- RESULTS TABLE (Must be after profiles and exams)
CREATE TABLE Result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Profile_id UUID REFERENCES profiles(id) NOT NULL, -- Link to the Candidate profile
    Evaluation_id BIGINT REFERENCES Evaluation(id) NOT NULL,
    Score float,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE results ENABLE ROW LEVEL SECURITY; -- Enable RLS for Results



-- ====================================================================
-- 4. RLS POLICIES
-- ====================================================================

-- --- PROFILES POLICIES ---
-- 1. Allow authenticated user to create their own profile upon signup
CREATE POLICY "Allow public insert on own profile" ON profiles 
    FOR INSERT WITH CHECK (auth.uid() = id);

-- 2. Allow users to view their own profile
CREATE POLICY "Users can view own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);

-- 3. Allow Admin/Recruiter to view all profiles
CREATE POLICY "Admin/Recruiter can view all profiles" ON profiles
    FOR SELECT USING (public.is_admin_or_recruiter());

-- 4. Allow user to update only their own profile metadata (first_name, last_name)
-- IMPORTANT: Role and is_role_finalized can only be changed via the finalize_role() RPC
CREATE POLICY "Users can update own profile metadata only" ON profiles
    FOR UPDATE USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- --- RESULTS POLICIES ---
-- 1. Allow Admin/Recruiter to view all results
CREATE POLICY "Admin/Recruiter can view all results" ON results
    FOR SELECT USING (public.is_admin_or_recruiter());

-- 2. Allow Candidates to view only their own results
CREATE POLICY "Candidates can view own results" ON results
    FOR SELECT USING (auth.uid() = candidate_id AND NOT public.is_admin_or_recruiter());

-- --- EXAMS POLICIES ---
-- 1. Allow everyone to view exams (Recruiters/Candidates need this)
CREATE POLICY "Allow all authenticated users to view exams" ON exams
    FOR SELECT USING (auth.role() = 'authenticated');
    
-- 2. Allow Admin/Recruiter to manage (INSERT/UPDATE/DELETE) exams
CREATE POLICY "Admin/Recruiter can manage exams" ON exams
    FOR ALL USING (public.is_admin_or_recruiter());

-- --- QUESTIONS POLICIES ---
-- 1. Allow all authenticated users to view questions (candidates need to see exam questions)
CREATE POLICY "Allow all authenticated users to view questions" ON questions
    FOR SELECT USING (auth.role() = 'authenticated');

-- 2. Allow Admin/Recruiter to manage (INSERT/UPDATE/DELETE) questions
CREATE POLICY "Admin/Recruiter can manage questions" ON questions
    FOR ALL USING (public.is_admin_or_recruiter());

-- ====================================================================
-- 5. AUTH TRIGGER & RPC
-- ====================================================================

-- Function to automatically create a profile row when a new user signs up.
-- Relies on the table's DEFAULT values for 'role' and 'is_role_finalized'.
-- Splits full_name from user metadata into first_name and last_name.
CREATE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
DECLARE
  full_name TEXT;
  name_parts TEXT[];
BEGIN
  -- Extract full_name from raw_user_meta_data
  full_name := NEW.raw_user_meta_data->>'full_name';
  
  -- Split name into parts if it exists
  IF full_name IS NOT NULL AND full_name != '' THEN
    name_parts := string_to_array(trim(full_name), ' ');
    
    -- Insert profile with split names
    INSERT INTO public.profiles (id, first_name, last_name)
    VALUES (
      NEW.id,
      name_parts[1],
      CASE 
        WHEN array_length(name_parts, 1) > 1 
        THEN array_to_string(name_parts[2:array_length(name_parts, 1)], ' ')
        ELSE NULL
      END
    );
  ELSE
    -- Insert profile without names
    INSERT INTO public.profiles (id)
    VALUES (NEW.id);
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger: Call handle_new_user() after a new user is created in auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- RPC function to allow a user to finalize their role choice.
CREATE FUNCTION public.finalize_role(new_role TEXT)
RETURNS void AS $$
BEGIN
  UPDATE public.profiles
  SET
    role = new_role,
    is_role_finalized = TRUE
  WHERE id = auth.uid();
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to check if current user is admin/recruiter (avoids RLS recursion)
CREATE FUNCTION public.is_admin_or_recruiter()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS(
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid()
    AND role IN ('admin', 'recruiter')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Disable RLS temporarily to allow the trigger to run (best practice)
ALTER FUNCTION public.handle_new_user() SET search_path = public, ext_http;
ALTER FUNCTION public.finalize_role(TEXT) SET search_path = public, ext_http;
